### ISSUE TITLE
Standalone testing infrastructure for EVMJIT

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/evmjit#43] opened 2016-04-20 21:31 UTC
We should have a standalone test infrastructure for EVMJIT, so that we can run automated tests with only the single repository, and so that developers can run the tests based purely on cloning this single repository.

`make test`, `test.sh` or whatever.

**Comment by chriseth** [comment] 2016-04-21 09:26
Duplicate of https://github.com/ethereum/evmjit/issues/34

**Closed by chriseth** 2016-04-21 09:26 UTC
Labels: enhancement
